// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBaseStationToGroup(arg1, arg2) {
  return window['go']['main']['App']['AddBaseStationToGroup'](arg1, arg2);
}

export function ChangeBaseStationChannel(arg1, arg2) {
  return window['go']['main']['App']['ChangeBaseStationChannel'](arg1, arg2);
}

export function ChangeBaseStationPowerStatus(arg1, arg2) {
  return window['go']['main']['App']['ChangeBaseStationPowerStatus'](arg1, arg2);
}

export function CreateGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateGroup'](arg1, arg2);
}

export function EnableBluetooth() {
  return window['go']['main']['App']['EnableBluetooth']();
}

export function ForceUpdate() {
  return window['go']['main']['App']['ForceUpdate']();
}

export function ForgetBaseStation(arg1) {
  return window['go']['main']['App']['ForgetBaseStation'](arg1);
}

export function GetConfiguration() {
  return window['go']['main']['App']['GetConfiguration']();
}

export function GetFoundBaseStations() {
  return window['go']['main']['App']['GetFoundBaseStations']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IdentitifyBaseStation(arg1) {
  return window['go']['main']['App']['IdentitifyBaseStation'](arg1);
}

export function InitBluetooth() {
  return window['go']['main']['App']['InitBluetooth']();
}

export function IsSteamVRConnected() {
  return window['go']['main']['App']['IsSteamVRConnected']();
}

export function IsSteamVRConnectivityAvailable() {
  return window['go']['main']['App']['IsSteamVRConnectivityAvailable']();
}

export function IsUpdatingSupported() {
  return window['go']['main']['App']['IsUpdatingSupported']();
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function RemoveGroup(arg1) {
  return window['go']['main']['App']['RemoveGroup'](arg1);
}

export function RenameGroup(arg1, arg2) {
  return window['go']['main']['App']['RenameGroup'](arg1, arg2);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function SleepAllBaseStations() {
  return window['go']['main']['App']['SleepAllBaseStations']();
}

export function StartScanFor10Seconds() {
  return window['go']['main']['App']['StartScanFor10Seconds']();
}

export function ToggleSteamVRManagement() {
  return window['go']['main']['App']['ToggleSteamVRManagement']();
}

export function ToggleTray() {
  return window['go']['main']['App']['ToggleTray']();
}

export function UpdateBaseStationParam(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateBaseStationParam'](arg1, arg2, arg3);
}

export function UpdateConfigValue(arg1, arg2) {
  return window['go']['main']['App']['UpdateConfigValue'](arg1, arg2);
}

export function UpdateGroupManagedFlags(arg1, arg2) {
  return window['go']['main']['App']['UpdateGroupManagedFlags'](arg1, arg2);
}

export function WakeUpAllBaseStations() {
  return window['go']['main']['App']['WakeUpAllBaseStations']();
}
